home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('<int:post_pk>', views.postdetail, name="postdetail"),
]

lohproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models


class Post(models.Model):
    image = models.ImageField(upload_to='posts/images/')
    url = models.URLField(blank=True)
    name = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.name

class Main(models.Model):
    logo = models.ImageField(upload_to='main/', null=True)
    url = models.URLField(blank=True)
    sname = models.CharField(max_length=200, null=True)
    firsttext = models.CharField(max_length=200, null=True)
    telegram = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    address = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=20)
    about_title = models.CharField(max_length=50, null=True)
    about = models.TextField(null=True)

    def __str__(self):
        return self.sname

home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Main


def home(request):
    posts = Post.objects.all().order_by('-id')[:3]
    mains = Main.objects.get(id=1)
    return render(request, 'home.html', {'posts':posts, 'mains':mains})

def postdetail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    mains = Main.objects.get(id=1)
    return render(request, 'postdetail.html', {'post':post, 'mains':mains})

def posts(request):
    posts = Post.objects.all().order_by('-id')
    mains = Main.objects.get(id=1)
    return render(request, 'posts.html', {'posts':posts, 'mains':mains})

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>شرکت لوح رایانه پلدشت</title>
  <meta content="فروش انواع قطعات کامپیوتر و لوازم جانبی موبایل" name="descriptison">
  <meta content="کامپیوتر, قطعات کامپیوتر, پلدشت, شرکت, پاوربانک, پرینتر, لپتاپ" name="keywords">
  <meta property="og:image:alt" content="Loh Rayane Poldasht" />
  <meta property="og:url" content="https://lohrayanecorp.ir/" />

  <!-- Favicons -->
  <link href="{{ mains.logo.url }}" rel="icon">
  <link href="{{ mains.logo.url }}" rel="logo">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/aos/aos.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
</head>
<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top ">
    <div class="container d-flex">
      <div style="font-family: 'Cairo', sans-serif;" class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">{{ mains.email|safe }}</a>
        <i class="icofont-phone"></i> {{ mains.phonenumber }}
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="telegram"><i class="icofont-telegram"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></i></a>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <a href="/"><h1 class="logo mr-auto"><img src="{{ mains.logo.url }}" width="30" height="30"></a>
        <span style="font-size:16px; color:white; font-family: 'Cairo', sans-serif;"> {{ mains.sname }}</span></h1></a>
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      <nav class="nav-menu d-none d-lg-block">
        <ul>
		        <li style="text-align: center;"class="active"><a href="/">خانه</a></li>
            <li><a style="text-align: center;" href="#about">درباره ما</a></li>
            <li><a style="text-align: center;" href="#portfolio">فعالیت ها</a></li>
            <li><a style="text-align: center;" href="#contact">ارتباط باما</a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="500">
      <h1 style="text-align: center;"> {{ mains.firsttext|safe }} </h1>
      <div style="text-align: center;"><a href="#about" class="btn-get-started scrollto">درباره ما</a></div>
    </div>
  </section>
  <!-- End Hero -->

  <main id="main">
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="row">
          <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left">
            <img src="{% static 'home/img/about.jpg' %}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content" data-aos="fade-right">
            <div style="text-align:right;"><h3>{{ mains.about_title|safe }}</h3></div>
            <div style="text-align:right;"><p>
              {{ mains.about|safe }}
            </p>
            </div>
          </div>
        </div>

      </div>
    </section><!--



    --><section id="portfolio" class="portfolio">
      <div class="container">
        <div class="section-title">
		  <h2 class="mt-5">آخرین فعالیت ها</h2>
			<hr>
			<div class="row">
        {% for p in posts %}
				<div class="col-lg-4 col-md-6">
          {% if p.url %}
              <a href="{{ p.url }}">
				      <img src="{{ p.image.url }}" class="img-fluid mb-2">
				      </a>
          {% else %}
          <img src="{{ p.image.url }}" class="img-fluid mb-2">
          {% endif %}
          <a href="{% url 'home:postdetail' p.id %}"><h3 style="text-align: right;">{{ p.title|safe }}</h3></a>
				</div>
        {% endfor %}
			</div>
      <p>
			<br>
			<div class="container position-relative" data-aos="fade-up" data-aos-delay="500">
			<a href="{% url 'home:posts' %}"><button type="button" class="btn btn-outline-danger" style="text-align:center">مشاهده همه</button></a>
		</div>
		</div>

      </div>

    </section><!-- End Portfolio Section -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">
        <div class="section-title">
          <h2>ارتباط با ما</h2>
        </div>
        <div class="row" data-aos="fade-up">
          <div class="col-lg-6">
            <div class="info-box mb-4">
              <i class="bx bx-map"></i>
              <h3>آدرس ما</h3>
              <p>{{ mains.address|safe }}</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="info-box  mb-4">
              <i class="bx bx-envelope"></i>
              <h3>ایمیل ما</h3>
              <p style="font-family: 'Cairo', sans-serif;">{{ mains.email }}</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="info-box  mb-4">
              <i class="bx bx-phone-call"></i>
              <h3>شماره تماس</h3>
              <p>{{ mains.phonenumber|safe }}</p>
            </div>
          </div>
        </div>
        <div class="row" data-aos="fade-up">

          <div class="col-lg-6 ">
            <iframe class="mb-4 mb-lg-0" src="https://maps.google.com/maps?q=poldasht&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe>
          </div>
        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <a href="/"><img src="{% static 'home/img/logo.png' %}" width="50" height="50"></a>
			            <br>
                  <br>
              <p>
                {{ mains.address|safe }}
                <br><br>
                <strong>{{ mains.phonenumber|safe }}</strong> :تلفن<br>
                 <strong style="font-family: 'Cairo', sans-serif;"> {{ mains.email }}</strong> :ایمیل <br>
               </p>
                <div class="social-links mt-3">
                  <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
                  <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6">
              <div class="footer-info">
                 <img src="{% static 'home/img/m.png' %}" width="70" height="51">
  			            <br>
                    <br>
                <p>
                  طراحی انواع وبسایت برای کسب و کار شما
                  <br><br>
                  <a href="mailto:tuircorp@gmail.com"><strong style="font-family: 'Cairo', sans-serif;"> tuircorp@gmail.com</strong></a> :ایمیل <br>
                 </p>
                 <strong style="font-family: 'Cairo', sans-serif;"> www.TuirCorp.ir</strong>
                 <p>
                 <div class="social-links mt-3">
                   <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
                 </div>
                </div>
              </div>

              <div class="col-lg-4 col-md-6">
                <div class="footer-info" style="border-top:0px">
                  <img src="{% static 'home/img/Azerbaycan.png' %}" width="140" height="223">
                    
                </div>
              </div>
        </div>
      </div>

      <div class="container">
        <div style="font-family: 'Cairo', sans-serif;"class="copyright">
          &copy; Copyright <strong><span>Loh Rayane</span></strong>. All Rights Reserved
        </div>
        <div style="font-family: 'Cairo', sans-serif;" class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
          Designed by <a href="">Tuircorp.ir</a>
        </div>
      </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
<script  src = "{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
<script src = "{% static 'home/vendor/jquery/jquery.min.js' %}"> </script>
<script src = "{% static 'home/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src = "{% static 'home/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src = "{% static 'home/vendor/venobox/venobox.min.js' %}"></script>
<script src = "{% static 'home/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src = "{% static 'home/vendor/aos/aos.js' %}"></script>
<!-- Template Main JS File -->
<script src="{% static 'home/js/main.js' %}"></script>

</body>
</html>

home/templates/postdetail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>شرکت لوح رایانه پلدشت</title>
  <meta content="فروش انواع قطعات کامپیوتر و لوازم جانبی موبایل" name="descriptison">
  <meta content="کامپیوتر, قطعات کامپیوتر, پلدشت, شرکت, پاوربانک, پرینتر, لپتاپ" name="keywords">
  <meta property="og:image:alt" content="Loh Rayane Poldasht" />
  <meta property="og:url" content="https://lohrayanecorp.ir/faaliyat/" />

  <!-- Favicons -->
  <link href="{{ mains.logo.url }}" rel="icon">
  <link href="{{ mains.logo.url }}" rel="logo">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/aos/aos.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
  <!-- =======================================================
  ======================================================== -->
</head>
<body>
  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top header-inner-pages">
    <div class="container d-flex">
      <div style="font-family: 'Cairo', sans-serif;" class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">{{ mains.email|safe }}</a>
        <i class="icofont-phone"></i> {{ mains.phonenumber }}
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="telegram"><i class="icofont-telegram"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></i></a>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <a href="/"><h1 class="logo mr-auto"><img src="{{ mains.logo.url }}" width="30" height="30"></a>
        <span style="font-size:16px; color:white; font-family: 'Cairo', sans-serif;"> {{ mains.sname }}</span></h1></a>
      <!-- Uncomment below if you prefer to use an image logo -->
      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li style="text-align: center;"class="active"><a href="/">خانه</a></li>
          <li><a style="text-align: center;" href="/">درباره ما</a></li>
          <li><a style="text-align: center;" href="{% url 'home:posts' %}">فعالیت ها</a></li>
          <li><a style="text-align: center;" href="#contact">ارتباط باما</a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

<main id="main">
    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">
	  <p>
	  <br>
	  <p>
	  <br>
        <div class="portfolio-details-container">
          <div class="owl-carousel portfolio-details-carousel">
            <img src="{{ post.image.url }}">
          </div>
        </div>
        <div class="portfolio-description">
          <div style="text-align:right;">
              {{ post.content | safe }}
          </div>
        </div>
    </section>
  </main>

  
<!-- ======= Footer ======= -->
<footer id="footer">
  <div class="footer-top">
    <div class="container" id="contact">
      <div class="row">

        <div class="col-lg-4 col-md-6">
          <div class="footer-info">
            <a href="/"><img src="{% static 'home/img/logo.png' %}" width="50" height="50"></a>
                <br>
                <br>
            <p>
              {{ mains.address|safe }}
              <br><br>
              <strong>{{ mains.phonenumber|safe }}</strong> :تلفن<br>
               <strong style="font-family: 'Cairo', sans-serif;"> {{ mains.email }}</strong> :ایمیل <br>
             </p>
              <div class="social-links mt-3">
                <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <img src="{% static 'home/img/m.png' %}" width="70" height="51">
                  <br>
                  <br>
              <p>
                طراحی انواع وبسایت برای کسب و کار شما
                <br><br>
                <a href="mailto:tuircorp@gmail.com"><strong style="font-family: 'Cairo', sans-serif;"> tuircorp@gmail.com</strong></a> :ایمیل <br>
               </p>
               <strong style="font-family: 'Cairo', sans-serif;"> www.TuirCorp.ir</strong>
               <p>
               <div class="social-links mt-3">
                 <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
               </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6">
              <div class="footer-info" style="border-top:0px">
                <img src="{% static 'home/img/Azerbaycan.png' %}" width="140" height="223">
                  
              </div>
            </div>
      </div>
    </div>

      <div class="container">
        <div style="font-family: 'Cairo', sans-serif;"class="copyright">
          &copy; Copyright <strong><span>Loh Rayane</span></strong>. All Rights Reserved
        </div>
        <div style="font-family: 'Cairo', sans-serif;" class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
          Designed by <a href="">Tuircorp.ir</a>
        </div>
      </div>
    </footer><!-- End Footer -->

      <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
      <div id="preloader"></div>

   <!-- Vendor JS Files -->
  <script  src = "{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
  <script  src = "{% static 'home/vendor/jquery/jquery.min.js' %}"> </script>
  <script src = "{% static 'home/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src = "{% static 'home/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src = "{% static 'home/vendor/venobox/venobox.min.js' %}"></script>
  <script src = "{% static 'home/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src = "{% static 'home/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'home/js/main.js' %}"></script>
  <!-- other scripts -->
  </body>
  </html>

home/templates/posts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>شرکت لوح رایانه پلدشت</title>
  <meta content="فروش انواع قطعات کامپیوتر و لوازم جانبی موبایل" name="descriptison">
  <meta content="کامپیوتر, قطعات کامپیوتر, پلدشت, شرکت, پاوربانک, پرینتر, لپتاپ" name="keywords">
  <meta property="og:image:alt" content="Loh Rayane Poldasht" />
  <meta property="og:url" content="https://lohrayanecorp.ir/faaliyatha" />

  <!-- Favicons -->
  <link href="{{ mains.logo.url }}" rel="icon">
  <link href="{{ mains.logo.url }}" rel="logo">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/aos/aos.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
  <!-- =======================================================
  ======================================================== -->
</head>
<body>
  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top header-inner-pages">
    <div class="container d-flex">
      <div style="font-family: 'Cairo', sans-serif;" class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">{{ mains.email|safe }}</a>
        <i class="icofont-phone"></i> {{ mains.phonenumber }}
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="telegram"><i class="icofont-telegram"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></i></a>
      </div>
    </div>
  </div>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <a href="/"><h1 class="logo mr-auto"><img src="{{ mains.logo.url }}" width="30" height="30"></a>
        <span style="font-size:16px; color:white; font-family: 'Cairo', sans-serif;"> {{ mains.sname }}</span></h1></a>
      <!-- Uncomment below if you prefer to use an image logo -->
      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li style="text-align: center;"class="active"><a href="/">خانه</a></li>
          <li><a style="text-align: center;" href="/">درباره ما</a></li>
          <li><a style="text-align: center;" href="{% url 'home:posts' %}">فعالیت ها</a></li>
          <li><a style="text-align: center;" href="#contact">ارتباط باما</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

<main id="main">
  <p><p><p>

<section id="portfolio" class="portfolio">
  <div class="container">
    <div class="section-title">
  <h2 class="mt-5">فعالیت ها</h2>
  <hr>
  <div class="row">
    {% for p in posts %}
    <div class="col-lg-4 col-md-6">
      {% if p.url %}
          <a href="{{ p.url }}">
          <img src="{{ p.image.url }}" class="img-fluid mb-2">
          </a>
      {% else %}
      <img src="{{ p.image.url }}" class="img-fluid mb-2">
      {% endif %}
      <a href="{% url 'home:postdetail' p.id %}"><h3 style="text-align: right;">{{ p.title|safe }}</h3></a>
    </div>
    {% endfor %}
  </div>
  </div>
  <br>
</div>
</section>
</main>
<!-- ======= Footer ======= -->
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-4 col-md-6">
          <div class="footer-info">
            <a href="/"><img src="{% static 'home/img/logo.png' %}" width="50" height="50"></a>
                <br>
                <br>
            <p>
              {{ mains.address|safe }}
              <br><br>
              <strong>{{ mains.phonenumber|safe }}</strong> :تلفن<br>
               <strong style="font-family: 'Cairo', sans-serif;"> {{ mains.email }}</strong> :ایمیل <br>
             </p>
              <div class="social-links mt-3">
                <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <img src="{% static 'home/img/m.png' %}" width="70" height="51">
                  <br>
                  <br>
              <p>
                طراحی انواع وبسایت برای کسب و کار شما
                <br><br>
                <a href="mailto:tuircorp@gmail.com"><strong style="font-family: 'Cairo', sans-serif;"> tuircorp@gmail.com</strong></a> :ایمیل <br>
               </p>
               <strong style="font-family: 'Cairo', sans-serif;"> www.TuirCorp.ir</strong>
               <p>
               <div class="social-links mt-3">
                 <a href="#" class="telegram"><i class="bx bxl-telegram"></i></a>
               </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6">
              <div class="footer-info" style="border-top:0px">
                <img src="{% static 'home/img/Azerbaycan.png' %}" width="140" height="223">
                  
              </div>
            </div>
      </div>
    </div>

    <div class="container">
      <div style="font-family: 'Cairo', sans-serif;"class="copyright">
        &copy; Copyright <strong><span>Loh Rayane</span></strong>. All Rights Reserved
      </div>
      <div style="font-family: 'Cairo', sans-serif;" class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
        Designed by <a href="">Tuircorp.ir</a>
      </div>
    </div>
  </footer><!-- End Footer -->


    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
    <div id="preloader"></div>

 <!-- Vendor JS Files -->
<script  src = "{% static 'home/vendor/jquery/jquery.min.js' %}"> </script>
<script src = "{% static 'home/vendor/jquery/jquery.min.js' %}"> </script>
<script src = "{% static 'home/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src = "{% static 'home/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src = "{% static 'home/vendor/venobox/venobox.min.js' %}"></script>
<script src = "{% static 'home/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src = "{% static 'home/vendor/aos/aos.js' %}"></script>

 <!-- Template Main JS File -->

 <script src="{% static 'home/js/main.js' %}"></script>
 <!-- other scripts -->
</body>
</html>